name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/crimeapp:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/crimeapp:latest

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/crimeapp:latest \
          --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io

